name: Bug Report
title: "[BUG] <TITLE>"
description: State if something is wrong
projects:
  - "DrKJeff16/6"
labels:
  - bug
  - important
  - needs-triage
assignees:
  - DrKJeff16
body:
  - type: textarea
    attributes:
      label: Description
      description: |
        Write down what happened, as detailed as you can. Avoid irrelevant info!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe clearly what were you expecting to occur.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Please list the steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        If there's more info you could tell, please do. Add screenshots too, if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Plugin Setup
      description: |
        If the plugin itself is causing an issue
        please paste the relevant code snippet showing how you configured this plugin.
      value: |
        require('project_nvim').setup()
      render: lua
    validations:
      required: false
  - type: textarea
    attributes:
      label: Health Check
      description: |
        If you can run `:checkhealth project`, please paste the output below.
      placeholder: "<PASTE HERE IF POSSIBLE>"
      render:
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
  - type: checkboxes
    attributes:
      label: Issue Checks
      description: |
        Make sure to read every checkbox and answer truthfully.
      options:
        - label: I am running on the latest version of `project.nvim`
          required: true
        - label: I have checked for existing issues related to this one, whether open or closed
          required: true
        - label: I have read the pertinent documentation (`README.md`, `:h project-nvim`, etc.)
          required: true
  - type: checkboxes
    attributes:
      label: Issue Type
      description: |
        What does your issue relate to? Select one at least!
      options:
        - label: The plugin is not detecting directories correctly
          required: false
        - label: The plugin is not changing directories
          required: false
        - label: Logging issues
          required: false
        - label: UI errors
          required: false
        - label: Another plugin interferes with `project.nvim`
          required: false
        - label: Project history broke
          required: false
        - label: The Telescope picker is having issues
          required: false
        - label: "`fzf-lua` integration issues"
          required: false
        - label: Windows is causing undesirable behaviour
          required: false
        - label: Documentation needs a revision
          required: false
        - label: Other
          required: false
  - type: input
    attributes:
      label: Operating System
      description: |
        Please indicate your OS. Add the version if applicable.
      placeholder: Linux 6.15.6-arch1-1
    validations:
      required: true
  - type: input
    attributes:
      label: Neovim Version
      description: |
        Paste the output of `nvim -v | head -n 1 | cut -d ' ' -f2-`.
      placeholder: v0.12.0-dev-839+ga08d6a8ac1
    validations:
      required: true
# vim: set ts=2 sts=2 sw=2 et ai si sta:
