name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] <TITLE>"
labels:
  - enhancement
  - feature-request
assignees:
  - DrKJeff16
body:
  - type: textarea
    attributes:
      label: Description
      description: |
        Write down, as detailed as you can, what is it that you wish to be implemented.
        Be as concise as possible, and give the necessary context.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Potential Improvements
      description: |
        Describe clearly how would this plugin benefit from your suggestion
        and what kinds of users, if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Related Issues
      description: |
        If applicable, please list the issue(s) that your suggestion could fix.
      placeholder: |
        - #1
        - #2
        ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: |
        Please describe any alternative solutions you have considered, if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code Implementation
      description: |
        If possible, please include your solution in Lua code.
        You will be credited if so.
      value: |
        -- LEAVE THIS UNCHANGED IF THERE IS NO CODE YOU CAN INCLUDE
        require('project.foo').bar()
      render: lua
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        If there's more info you could tell, please do. Add screenshots too, if applicable.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
  - type: checkboxes
    attributes:
      label: Issue Checks
      options:
        - label: I have read the docs (`README.md`, `:h project-nvim`, etc.)
          required: true
        - label: I have checked for existing issues related to this one, whether open or closed
          required: true
  - type: input
    attributes:
      label: Operating System
      description: |
        Please indicate your OS. Add the version if applicable.
      placeholder: Linux 6.15.6-arch1-1
    validations:
      required: true
  - type: input
    attributes:
      label: Neovim Version
      description: |
        Paste the output of `nvim -v | head -n 1 | cut -d ' ' -f2-`.
      placeholder: v0.12.0-dev-839+ga08d6a8ac1
    validations:
      required: true
# vim: set ts=2 sts=2 sw=2 et ai si sta:
