blank_issues_enabled: true
contact_links:
  - name: Have a question?
    url: https://github.com/DrKJeff16/project.nvim/discussions
    about: Use GitHub Discussions instead
  - name: Contributing Guidelines
    url: https://github.com/DrKJeff16/project.nvim/blob/main/CONTRIBUTING.md
    about: Make sure to read them before opening an issue
  - name: Code of Conduct
    url: https://github.com/DrKJeff16/project.nvim/blob/main/CODE_OF_CONDUCT.md
    about: Please read and follow our Code of Conduct
# vim: set ts=2 sts=2 sw=2 et ai si sta:
