name: Action Release
on:
  push:
    tags:
      - "v*.*.*"
  merge_group:
    branches:
      - main
  release:
    types:
      - created
permissions:
  contents: write
  discussions: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build Project Assets
        run: |
          mkdir -pv project.nvim
          cp -rv lua doc README.md CREDITS.md LICENSE Makefile project.nvim
          zip -r -9 project.nvim.zip project.nvim
          tar cvJf project.nvim.tar.xz project.nvim
          tar cvzf project.nvim.tar.gz project.nvim
          7z a -mx9 -mmt -sdel project.nvim.7z project.nvim
          sha512sum project.nvim.7z project.nvim.zip project.nvim.tar.xz project.nvim.7z project.nvim.tar.gz >| sha512sums.txt
          md5sum project.nvim.7z project.nvim.zip project.nvim.tar.xz project.nvim.7z project.nvim.tar.gz >| md5sums.txt
      - name: Get Release
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true
          prerelease: true
          pattern: "^v.*"
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            md5sums.txt
            sha512sums.txt
            project.nvim.7z
            project.nvim.tar.gz
            project.nvim.tar.xz
            project.nvim.zip
# vim: set ts=2 sts=2 sw=2 et ai si sta:
