name: Stylua
on:
  push:
    paths:
      - "**.lua"
      - ".github/workflows/stylua.yml"
      - ".stylua.toml"
      - "stylua.toml"
  pull_request:
    paths:
      - "**.lua"
      - ".github/workflows/stylua.yml"
      - ".stylua.toml"
      - "stylua.toml"
jobs:
  stylua_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
# vim: set ts=2 sts=2 sw=2 et ai si sta:
