name: Run vim-eof-comment
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  vim_eof_comment:
    name: vim-eof-comment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.14"
      - name: Install vim-eof-comment
        run: |
          python -m pip install -U pip
          pip install -U vim-eof-comment
      - name: Run vim-eof-comment
        run: |
          vim-eof-comment -e lua,Makefile,yaml,yml,toml -i lua:2:Y -v .
          vim-eof-comment -e md -nv .
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "chore: format files with `vim-eof-comment`"
          commit_options: "--signoff"
          branch: ${{ github.head_ref }}
# vim: set ts=2 sts=2 sw=2 et ai si sta:
